import { readFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { describe, expect, test } from 'vitest';

/**
 * styles/_fonts.css points at faces that exist, by a URL the browser can follow.
 *
 * Both halves have been wrong. The file is generated by
 * tools/design/vendor_assets.py, which emitted `url('../fonts/…')` — correct
 * under Flask, where the sheet was served from /static/css/, and wrong ever
 * since: the compiled sheet is /_next/static/css/<hash>.css, so the same token
 * resolves to /_next/static/fonts/ and 404s. Next does not rewrite these, so
 * whatever is in the source is what the browser gets.
 *
 * Nothing fails loudly when that happens. The page renders, in a fallback
 * serif, with every Material Symbols ligature spelled out as its own name —
 * the same screen-full of stray words the icon subset produces when a name is
 * missing from it, and the reason this is asserted rather than eyeballed.
 *
 * The committed CSS was right while the generator was wrong, so this guards the
 * committed file: a regeneration that reintroduces the relative form fails here
 * rather than at the next deploy.
 */

const ROOT = path.resolve(import.meta.dirname, '..');
const CSS = readFileSync(path.join(ROOT, 'styles/_fonts.css'), 'utf8');

const URLS = [...CSS.matchAll(/url\(['"]?([^'")]+)['"]?\)/g)].map((m) => m[1]);

describe('the vendored font faces', () => {
  test('are declared at all', () => {
    expect(URLS.length).toBeGreaterThan(0);
  });

  test('are same-origin — font-src is \'self\', so a remote face would be refused', () => {
    const remote = URLS.filter((u) => /^(https?:)?\/\//.test(u));
    expect(remote, `fetched from another origin: ${remote.join(', ')}`).toEqual([]);
  });

  test('are root-relative, not relative to the stylesheet', () => {
    const relative = URLS.filter((u) => !u.startsWith('/') && !u.startsWith('data:'));
    expect(
      relative,
      `these resolve against /_next/static/css/ and 404: ${relative.join(', ')}`,
    ).toEqual([]);
  });

  test('each resolve to a file that is actually in public/', () => {
    const missing = URLS.filter(
      (u) => u.startsWith('/') && !existsSync(path.join(ROOT, 'public', u)),
    );
    expect(missing, `declared but not on disk: ${missing.join(', ')}`).toEqual([]);
  });
});
