"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}

Watiq migration checklist (Structure.md §6, Security.md §10.1) — delete the
lines that do not apply, but read all of them first:

1. Revision 0001 is the frozen baseline: it applies Watiq.sql verbatim and is
   never edited and never autogenerated over. Every change is a new revision.

2. `alembic revision --autogenerate` is NOT used on this project. The schema
   carries RLS policies, column-level GRANTs, SECURITY DEFINER functions,
   triggers and security_invoker views, and autogenerate sees none of them —
   it would happily emit a migration that silently drops the access-control
   model. Write the SQL by hand.

3. If this revision creates a table, it almost certainly also needs:
     - ALTER TABLE ... ENABLE ROW LEVEL SECURITY;
     - the CREATE POLICY statements for citizen / staff / auditor / admin;
     - column-level GRANTs, not table-level (a citizen must not hold UPDATE
       on a status column);
   A new table without RLS is readable by every application role.

4. If this revision creates a view, it needs `WITH (security_invoker = true)`.
   Without it the view runs as its owner and bypasses the caller's RLS.

5. Never GRANT anything to the schema owner's role, and never make an
   application role the owner of a new object: RLS does not apply to owners.

6. downgrade() must be real or must raise. A downgrade that silently does
   nothing turns a failed deploy into a corrupt schema.

7. After merging, `make test-security` must still pass — it asserts the
   policy count and the citizen/staff isolation guarantees.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op  # noqa: F401
import sqlalchemy as sa  # noqa: F401
${imports if imports else ""}

revision: str = ${repr(up_revision)}
down_revision: str | None = ${repr(down_revision)}
branch_labels: str | Sequence[str] | None = ${repr(branch_labels)}
depends_on: str | Sequence[str] | None = ${repr(depends_on)}


def upgrade() -> None:
    ${upgrades if upgrades else "raise NotImplementedError('write the upgrade')"}


def downgrade() -> None:
    ${downgrades if downgrades else "raise NotImplementedError('write the downgrade, or raise deliberately')"}
