/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,jsx}",
    "./components/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        "accent-gold": "rgb(var(--w-c-accent-gold) / <alpha-value>)",
        "background": "rgb(var(--w-c-background) / <alpha-value>)",
        "error": "rgb(var(--w-c-error) / <alpha-value>)",
        "error-container": "rgb(var(--w-c-error-container) / <alpha-value>)",
        "gold-muted": "rgb(var(--w-c-gold-muted) / <alpha-value>)",
        "institutional-navy": "rgb(var(--w-c-institutional-navy) / <alpha-value>)",
        "inverse-on-surface": "rgb(var(--w-c-inverse-on-surface) / <alpha-value>)",
        "inverse-primary": "rgb(var(--w-c-inverse-primary) / <alpha-value>)",
        "inverse-surface": "rgb(var(--w-c-inverse-surface) / <alpha-value>)",
        "mediterranean-cerulean": "rgb(var(--w-c-mediterranean-cerulean) / <alpha-value>)",
        "midnight-navy": "rgb(var(--w-c-midnight-navy) / <alpha-value>)",
        "on-background": "rgb(var(--w-c-on-background) / <alpha-value>)",
        "on-error": "rgb(var(--w-c-on-error) / <alpha-value>)",
        "on-error-container": "rgb(var(--w-c-on-error-container) / <alpha-value>)",
        "on-primary": "rgb(var(--w-c-on-primary) / <alpha-value>)",
        "on-primary-container": "rgb(var(--w-c-on-primary-container) / <alpha-value>)",
        "on-primary-fixed": "rgb(var(--w-c-on-primary-fixed) / <alpha-value>)",
        "on-primary-fixed-variant": "rgb(var(--w-c-on-primary-fixed-variant) / <alpha-value>)",
        "on-secondary": "rgb(var(--w-c-on-secondary) / <alpha-value>)",
        "on-secondary-container": "rgb(var(--w-c-on-secondary-container) / <alpha-value>)",
        "on-secondary-fixed": "rgb(var(--w-c-on-secondary-fixed) / <alpha-value>)",
        "on-secondary-fixed-variant": "rgb(var(--w-c-on-secondary-fixed-variant) / <alpha-value>)",
        "on-surface": "rgb(var(--w-c-on-surface) / <alpha-value>)",
        "on-surface-variant": "rgb(var(--w-c-on-surface-variant) / <alpha-value>)",
        "on-tertiary": "rgb(var(--w-c-on-tertiary) / <alpha-value>)",
        "on-tertiary-container": "rgb(var(--w-c-on-tertiary-container) / <alpha-value>)",
        "on-tertiary-fixed": "rgb(var(--w-c-on-tertiary-fixed) / <alpha-value>)",
        "on-tertiary-fixed-variant": "rgb(var(--w-c-on-tertiary-fixed-variant) / <alpha-value>)",
        "outline": "rgb(var(--w-c-outline) / <alpha-value>)",
        "outline-variant": "rgb(var(--w-c-outline-variant) / <alpha-value>)",
        "primary": "rgb(var(--w-c-primary) / <alpha-value>)",
        "primary-container": "rgb(var(--w-c-primary-container) / <alpha-value>)",
        "primary-fixed": "rgb(var(--w-c-primary-fixed) / <alpha-value>)",
        "primary-fixed-dim": "rgb(var(--w-c-primary-fixed-dim) / <alpha-value>)",
        "secondary": "rgb(var(--w-c-secondary) / <alpha-value>)",
        "secondary-container": "rgb(var(--w-c-secondary-container) / <alpha-value>)",
        "secondary-fixed": "rgb(var(--w-c-secondary-fixed) / <alpha-value>)",
        "secondary-fixed-dim": "rgb(var(--w-c-secondary-fixed-dim) / <alpha-value>)",
        "sovereign-gold": "rgb(var(--w-c-sovereign-gold) / <alpha-value>)",
        "surface": "rgb(var(--w-c-surface) / <alpha-value>)",
        "surface-bright": "rgb(var(--w-c-surface-bright) / <alpha-value>)",
        "surface-container": "rgb(var(--w-c-surface-container) / <alpha-value>)",
        "surface-container-high": "rgb(var(--w-c-surface-container-high) / <alpha-value>)",
        "surface-container-highest": "rgb(var(--w-c-surface-container-highest) / <alpha-value>)",
        "surface-container-low": "rgb(var(--w-c-surface-container-low) / <alpha-value>)",
        "surface-container-lowest": "rgb(var(--w-c-surface-container-lowest) / <alpha-value>)",
        "surface-dim": "rgb(var(--w-c-surface-dim) / <alpha-value>)",
        "surface-tint": "rgb(var(--w-c-surface-tint) / <alpha-value>)",
        "surface-variant": "rgb(var(--w-c-surface-variant) / <alpha-value>)",
        "tertiary": "rgb(var(--w-c-tertiary) / <alpha-value>)",
        "tertiary-container": "rgb(var(--w-c-tertiary-container) / <alpha-value>)",
        "tertiary-fixed": "rgb(var(--w-c-tertiary-fixed) / <alpha-value>)",
        "tertiary-fixed-dim": "rgb(var(--w-c-tertiary-fixed-dim) / <alpha-value>)",
      },
      borderRadius: {
        "DEFAULT": "var(--w-r-DEFAULT)",
        "full": "var(--w-r-full)",
        "lg": "var(--w-r-lg)",
        "round-eight": "var(--w-r-round-eight)",
        "xl": "var(--w-r-xl)",
      },
      spacing: {
        "base": "var(--w-sp-base)",
        "container-max": "var(--w-sp-container-max)",
        "container-max-width": "var(--w-sp-container-max-width)",
        "gutter": "var(--w-sp-gutter)",
        "interpreter-slot-width": "var(--w-sp-interpreter-slot-width)",
        "lg": "var(--w-sp-lg)",
        "margin-desktop": "var(--w-sp-margin-desktop)",
        "margin-mobile": "var(--w-sp-margin-mobile)",
        "md": "var(--w-sp-md)",
        "sm": "var(--w-sp-sm)",
        "unit": "var(--w-sp-unit)",
        "xl": "var(--w-sp-xl)",
        "xs": "var(--w-sp-xs)",
      },
      fontFamily: {
        "body-lg": "var(--w-ff-body-lg)",
        "body-md": "var(--w-ff-body-md)",
        "body-sm": "var(--w-ff-body-sm)",
        "caption": "var(--w-ff-caption)",
        "display-lg": "var(--w-ff-display-lg)",
        "display-lg-mobile": "var(--w-ff-display-lg-mobile)",
        "headline-lg": "var(--w-ff-headline-lg)",
        "headline-lg-mobile": "var(--w-ff-headline-lg-mobile)",
        "headline-md": "var(--w-ff-headline-md)",
        "headline-sm": "var(--w-ff-headline-sm)",
        "headline-xl": "var(--w-ff-headline-xl)",
        "label-caps": "var(--w-ff-label-caps)",
        "label-md": "var(--w-ff-label-md)",
        "label-sm": "var(--w-ff-label-sm)",
        "mono": "var(--w-ff-mono)",
        "support-sm": "var(--w-ff-support-sm)",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
