import { tryGet } from '@/lib/api.js';
import { pageTitle } from '@/lib/metadata.js';
import { itemsOf, displayName } from '@/lib/format.js';
import { pageContext } from '@/lib/page.js';
import { requireLogin } from '@/lib/guards.js';
import { intOr, formatDate, formatMoney } from '@/lib/view.js';
import EmptyState from '@/components/EmptyState.jsx';
import StatusBadge from '@/components/StatusBadge.jsx';
import '@/styles/pages/payment_confirmation.css';

/**
 * Landing page after a payment. ?id selects one; otherwise show the latest.
 * Port of frontend_flask/templates/payment_confirmation.html and
 * views/citizen.py:payment_confirmation.
 *
 * Carries its own chrome — this is a receipt someone prints, and a sticky nav
 * and a floating accessibility widget across the top of a printed page are not
 * what anyone wants at a counter. print:hidden covers the rest.
 */

export const generateMetadata = pageTitle('Payment Receipt');

export default async function PaymentConfirmationPage({ searchParams }) {
  await requireLogin('/payments/confirmation');
  const params = await searchParams;
  const { t, profile } = await pageContext({ withUnread: false });

  const paymentId = intOr(params?.id, null);
  let payment = paymentId ? await tryGet(`/api/v1/payments/${paymentId}`, null) : null;
  if (!payment) {
    const items = itemsOf(await tryGet('/api/v1/payments', {}));
    payment = items[0] ?? null;
  }

  return (
    <div className="min-h-screen bg-surface-container-low flex flex-col">
      <main id="main" className="flex-1 w-full max-w-3xl mx-auto px-margin-mobile py-12 space-y-6">
        {!payment ? (
          <EmptyState
            icon="receipt_long"
            message={t('There is no payment to show a receipt for.')}
            action={{ href: '/payments', label: t('Go to payments') }}
          />
        ) : (
          <>
            <div className="text-center space-y-3 print:hidden">
              <div className="w-16 h-16 rounded-full bg-secondary-container text-on-secondary-container mx-auto flex items-center justify-center">
                <span aria-hidden="true" className="material-symbols-outlined text-[32px]">
                  {String(payment.status) === 'completed' ? 'check_circle' : 'schedule'}
                </span>
              </div>
              <h1 className="font-headline-lg text-headline-lg text-on-surface">
                {String(payment.status) === 'completed' ? t('Payment received') : t('Payment pending')}
              </h1>
            </div>

            <article className="bg-surface border border-outline-variant rounded-xl p-8 shadow-sm space-y-6">
      <header className="flex items-start justify-between gap-4 border-b border-outline-variant pb-6">
                <div>
                  <p className="font-label-caps text-label-caps text-on-surface-variant uppercase">
                    {t('Official receipt')}
                  </p>
                  <p className="font-mono text-headline-md text-on-surface">#{payment.id}</p>
                </div>
                <StatusBadge status={payment.status} />
              </header>

              <dl className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                {[
                  [t('Service'), payment.service_name],
                  [t('Amount'), formatMoney(payment.amount, payment.currency ?? 'TND')],
                  [t('Paid'), formatDate(payment.paid_at, { withTime: true })],
                  [t('Paid by'), profile ? displayName(profile) : '—'],
                ].map(([label, value]) => (
                  <div key={label}>
                    <dt className="font-label-sm text-label-sm text-on-surface-variant uppercase tracking-wide">
                      {label}
                    </dt>
                    <dd className="font-body-lg text-body-lg text-on-surface">{value || '—'}</dd>
                  </div>
                ))}
              </dl>

              <p className="font-support-sm text-support-sm text-on-surface-variant border-t border-outline-variant pt-6">
                {t('Quote the receipt number above when collecting your document. This receipt is generated by the Watiq National Portal and does not require a stamp.')}
              </p>
            </article>

            <div className="flex flex-wrap gap-3 print:hidden">
              <a
                className="inline-flex items-center gap-2 bg-primary-container text-on-primary px-6 py-3 rounded font-label-md text-label-md hover:shadow-lg transition-all focus-ring"
                href="/requests"
              >
                <span aria-hidden="true" className="material-symbols-outlined">description</span>
                {t('Back to my requests')}
              </a>
              <a
                className="inline-flex items-center gap-2 border border-outline-variant px-6 py-3 rounded font-label-md text-label-md hover:bg-surface-container-low transition-colors focus-ring"
                href="/payments"
              >
                {t('All payments')}
              </a>
            </div>
          </>
        )}
      </main>
    </div>
  );
}
